#%RAML 1.0 Library
usage:
types:
  shoppingItemType: 
    properties:
      description:
        type: string
        required: true
      address:
        type:  string

    description: string
  
    